# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm" "kvm-intel" ];
  boot.kernelParams = [ "intel_iommu=on" "iommu=pt" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/vg0-lv0";
      fsType = "btrfs";
      options = [ "subvol=@" , "compress=zstd" , "ssd" , "space_cache=v2" , "noatime" , "discard=async" ];
    };
  
  fileSystems."/home" =
    { device = "/dev/mapper/vg0-lv0";
      fsType = "btrfs";
      options = [ "subvol=@home" , "compress=zstd" , "ssd" , "space_cache=v2" , "noatime" , "discard=async" ];
    };
  
  fileSystems."/var" =
    { device = "/dev/mapper/vg0-lv0";
      fsType = "btrfs";
      options = [ "subvol=@var" , "compress=zstd" , "ssd" , "space_cache=v2" , "noatime" , "discard=async" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/vg0-lv0";
      fsType = "btrfs";
      options = [ "subvol=@var_log" , "compress=zstd" , "ssd" , "space_cache=v2" , "noatime" , "discard=async" ];
    };
  
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3C1C-B325";
      fsType = "vfat";
      
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/vg0-swp0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
